### PR TITLE
Update about-the-plan.js

### LINKED ISSUE #76: Update about us foot notes / links
Text [here](https://docs.google.com/document/d/1ctl8C8fdI7GHxYnj0frSxt72isy-5lj1btt31o0jjx4/edit).

Foot notes [here](https://docs.google.com/spreadsheets/d/1HfrE2drgWT0253JinBBShP7g135ChNlA1G3GIYd73D0/edit#gid=0)

### PR DESCRIPTION
**Pull request by martincollignon**
fixes #76

### CODE REVIEW

**Comment by Jacse** [comment]
The current foot note design does not support so many notes next to each other on the desktop view, so we'll need to update that before merging this.

image

**Comment by martincollignon** [comment]
We should use the original UX of "tiles" with your design? Seems like the
easiest, no?

**Comment by Jacse** [comment]
> We should use the original UX of "tiles" with your design? Seems like the easiest, no?

The easiest would be to make them appear on hover as in the design on Zeplin (similar to current UX on mobile). Whether that's better than tiles/carousels I don't know.

**Comment by Jacse** [comment]
In the interest of time, I've done that for now - we can always change to tiles.

**Pull request merged**
