### PR TITLE
Added share buttons under the CTA on the frontpage

### PR DESCRIPTION
**Pull request by magnuspaaske**
What it says. Added Font Awesome and made a module of share buttons

### CODE REVIEW

**Comment by Jacse** [comment]
Vi har faktisk allerede font awesome ikoner gennem `react-native-icons`, så det ville nok være bedst hvis vi bare havde det ene dependency. Du kan se et eksempel [her](https://github.com/Jacse/worlds-best-climate-plan/blob/1e6dd05ee5f0b92f040b22d693d84c2f085d2971/src/components/Form/Form.js#L3).

**Comment by magnuspaaske** [comment]
Removed font awesome. Not sure what the problem is with the yarn.lock file but the first time I ran `yarn` it seemed to remove a bunch of dependencies.

**Comment by Jacse** [comment]
There are conflicts in `yarn.lock`. Could you either remove your changes to `yarn.lock` or rebase?

**Comment by Jacse** [comment]
Har tilføjet til master og ændret designet en smule for at gøre det responsivt og gøre dem lidt mere subtile.

**Pull request closed without merging**
