### PR TITLE
First attempt to setup i18n

### PR DESCRIPTION
**Pull request by lodi-g**
This project is lacking i18n support however it would be great and useful to allow anyone to host it for their language. 

I recently e-mailed you about that and made a first attempt to setup i18n.

This is my first time interacting with Gatsby, so feel free to make feedback and question the choices made.

Thank you

### CODE REVIEW

**Comment by Jacse** [comment]
Hi @lodi-g,

Sorry I didn't get a chance to answer your e-mail yet! This looks good, but I think we should consider if it is really viable to do i18n on a per-paragraph basis. Since most of the components will need to be changed between languages (highlighted national newspapers, language-specific articles, links to petitions etc) it might make more sense to look into having per-language pages.

Have you taken a look at [The i18n Gatsby plugin](https://github.com/angeloocana/gatsby-plugin-i18n)? I allows us to create individual files per language. That should also help with SSR so it can be indexed on Google, shared on social media etc.

**Review by Jacse — COMMENTED** [review]
Hi @lodi-g,

Sorry I didn't get a chance to answer your e-mail yet! This looks good, but I think we should consider if it is really viable to do i18n on a per-paragraph basis. Since most of the components will need to be changed between languages (highlighted national newspapers, language-specific articles, links to petitions etc) it might make more sense to look into having per-language pages.

Have you taken a look at [The i18n Gatsby plugin](https://github.com/angeloocana/gatsby-plugin-i18n)? I allows us to create individual files per language. That should also help with SSR so it can be indexed on Google, shared on social media etc.

**Comment by lodi-g** [comment]
No worries about the e-mail! We all have lives with things to do!

I saw the i18n Gatsby plugin but I don't think it's appropriate: we're (as the CCL orgs) are taking the direction of a custom website for each country. Therefore, I'd rather fork the "template" (this repo) and translate directly the files: if I create a French version I don't need to care about the other languages. 

Maybe that'd even be a better way to handle i18n for these websites since, as you said, sources are differents, logo are differents etc.

Thoughts?

**Comment by Jacse** [comment]
I think that makes sense!

**Comment by lodi-g** [comment]
Thank you for your thoughts! I'll close the PR which is void now since this seems to be the consensus but feel free to comment anything else!
I'll go ahead and update my fork with the french translations and eventually rebase on yours if you make changes other than text stuff.

**Comment by Jacse** [comment]
Sounds like a great plan! Let me know if I can help.

**Pull request closed without merging**
